#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd.
#- Your script should only display username, user id and home directory path for the user.
filePath="/etc/passwd"
while IFS= read -r i; do
	echo "$i" | cut -d ":" -f 1,3,6
done < "$filePath"
