#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd, using the while loop + IFS.
filePath="/etc/passwd"
while IFS=: read -r username hasLoginPassword userId groupId userInfo userDirectory userShell; do
	echo "The user $username is part of the $groupId gang, lives in $userDirectory and rides $userShell. $userId's place is protected by the passcode $hasLoginPassword, more info about the user here: $userInfo"
done < "$filePath"
