#!/usr/bin/env bash
#Write a Bash script that displays:
#- The content of the current directory
#- In a list format
#- Where only the part of the name after the first dash is displayed 
if [ -a school ]; then
	echo "school file exists"
	
	if [ -s school ]; then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	
	if [ -f school ]; then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi

